
# TIERS MUST BE INTEGERS!!!
# delay should be provided in millis

hooks:
  1:
    durability: 64
    delay: 7500
    isUnbreakable: false
    power: 0.75

  2:
    durability: 96
    delay: 6000
    isUnbreakable: false
    power: 1

  3:
    durability: 120
    delay: 4500
    isUnbreakable: false
    power: 1.25
